name: CI - ORCID check & Playwright

on:
  pull_request:
    branches: [ master, chore/security-devdeps ]
  push:
    branches: [ chore/security-devdeps ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install root deps
        run: npm ci

      - name: Install playwright test deps
        run: |
          cd test/playwright || exit 0
          npm ci || true

      - name: Run ORCID encryption check
        run: |
          KEY=$(node -e "console.log(require('crypto').randomBytes(32).toString('base64'))")
          ORCID_TOKEN_KEY="$KEY" NODE_PATH=server/node_modules node test/check_orcid_encryption.js

      - name: Install Playwright browsers
        run: |
          cd test/playwright
          npx playwright install --with-deps

      - name: Run Playwright E2E
        run: |
          cd test/playwright
          npx playwright test --config ../../playwright.config.js --reporter=list

      - name: Audit (informational)
        run: npm audit --json | jq '.' || true
