name: Build Docker image

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR (optional)
        if: ${{ secrets.GITHUB_TOKEN != '' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: |
          docker build -f server/Dockerfile -t lspp-server:latest server
      - name: Save image metadata
        run: docker image ls --format "{{.Repository}}:{{.Tag}} {{.Size}}" | head -n 10
      - name: Push to GHCR (requires GHCR_PAT secret)
        if: ${{ secrets.GHCR_PAT }}
        run: |
          echo "Pushing to ghcr.io/${{ github.repository }}:latest"
          echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build -f server/Dockerfile -t ghcr.io/${{ github.repository }}:latest server
          docker push ghcr.io/${{ github.repository }}:latest
