name: Build Docker image

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      push:
        description: 'If true, push the built image to GHCR'
        required: false
        default: 'false'
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR (use GHCR_PAT if present, otherwise GITHUB_TOKEN)
        if: ${{ secrets.GHCR_PAT || secrets.GITHUB_TOKEN }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # Prefer GHCR_PAT (recommended), fall back to GITHUB_TOKEN if necessary
          password: ${{ secrets.GHCR_PAT || secrets.GITHUB_TOKEN }}
      - name: Build image
        run: |
          docker build -f server/Dockerfile -t lspp-server:latest server
      - name: Save image metadata
        run: docker image ls --format "{{.Repository}}:{{.Tag}} {{.Size}}" | head -n 10
      - name: Push to GHCR (manual or when GHCR_PAT present on master push)
        if: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.push == 'true') || (github.event_name == 'push' && github.ref == 'refs/heads/master' && secrets.GHCR_PAT) }}
        run: |
          echo "Pushing to ghcr.io/${{ github.repository }}:latest"
          docker build -f server/Dockerfile -t ghcr.io/${{ github.repository }}:latest server
          docker push ghcr.io/${{ github.repository }}:latest
