name: ORCID connect check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 1'

jobs:
  orcid-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start server
        env:
          TEST_BASE_URL: http://127.0.0.1:3010
        run: |
          npm ci --no-audit --no-fund || true
          # start server in background on port 3010 with dummy ORCID vars
          PORT=3010 ORCID_CLIENT_ID=test-client ORCID_CLIENT_SECRET=test-secret ORCID_REDIRECT_URI=http://127.0.0.1:3010/orcid/callback node server/index.js > /tmp/lspp-server.log 2>&1 &
          # wait for server health up to 15s
          for i in {1..15}; do
            if curl -sSf http://127.0.0.1:3010/health >/dev/null 2>&1; then
              echo "server is healthy"; break
            fi
            echo "waiting for server... ($i)"; sleep 1
          done
      - name: Check ORCID connect redirect
        env:
          TEST_BASE_URL: http://127.0.0.1:3010
        run: |
          node test/playwright/check_orcid_connect.js
*** End Patch