name: Render Cloak PNG

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'If true, commit the generated PNG back to the current branch'
        required: false
        default: 'false'

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install puppeteer
        run: npm install puppeteer --no-save

      - name: Render SVG to PNG
        run: |
          node tools/render-svg.js images/cloak_with_logo.svg images/cloak_with_logo_2000.png 2000

      - name: Upload PNG artifact
        uses: actions/upload-artifact@v4
        with:
          name: cloak-png
          path: images/cloak_with_logo_2000.png

      - name: Commit and push PNG (optional)
        if: ${{ github.event.inputs.commit == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add images/cloak_with_logo_2000.png
          git commit -m "feat(branding): add cloak PNG export 2000x2000 (via CI)" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}
